# Gradle Settings
org.gradle.jvmargs=-Xmx3G \
  --add-opens java.base/java.lang=ALL-UNNAMED \
  --add-opens java.base/java.lang.ref=ALL-UNNAMED \
  --add-opens java.base/java.util=ALL-UNNAMED \
  --add-opens java.base/java.lang.invoke=ALL-UNNAMED
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
# org.gradle.configuration-cache=true

# Minecraft & NeoForge Versions
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.120
neo_version_range=[21.1.120,)
loader_version_range=[4.0.35,)

# Mappings
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Mod Properties
mod_id=recolouredtooltips
mod_name=Recoloured Tooltips
mod_version=1.0
mod_authors=Darkhax, ongestalte
mod_license=LGPL v2.1
mod_description=Adds configurable default item tooltip colors. Neoforge 1.21.1 port of Coloured Tooltips.


# publishing
modLoaders=NeoForge
releaseType=release
curse_project=1203269